using GymManagement.BusinessLogic;
using GymManagement.Interfaces;
using GymManagement.Models;
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace GymManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly IUser _user;
        public UserController(IUser user) { _user = user; }

        // ── Image Upload ────────────────────────────────────────────
        // POST /User/UploadImage
        // Accepts: multipart form with field "file"
        // Saves to ~/Uploads/Users/<guid>.<ext>
        // Returns: { StatusCode, imagePath }
        // Limit: 5 MB enforced here and in Web.config maxRequestLength
        // POST /User/UploadImage
        // POST /User/UploadImage
        [HttpPost]
        [AllowAnonymous]
        [AllowCors] // ← CRITICAL for public registration
        public ActionResult UploadImage()
        {
            const long MaxBytes = 5 * 1024 * 1024;      // 5 MB

            try
            {
                // 1. Check if any file was sent
                if (Request.Files.Count == 0 || Request.Files[0].ContentLength == 0)
                    return Json(new { StatusCode = 400, Result = "No file received." });

                HttpPostedFileBase file = Request.Files[0];

                // 2. Size check
                if (file.ContentLength > MaxBytes)
                    return Json(new { StatusCode = 400, Result = $"File exceeds {MaxBytes / 1024 / 1024} MB limit." });

                // 3. Extension check
                string ext = Path.GetExtension(file.FileName).ToLower();
                string[] allowed = { ".jpg", ".jpeg", ".png", ".webp" };
                if (!allowed.Contains(ext))
                    return Json(new { StatusCode = 400, Result = "Only JPG, PNG, or WebP images are allowed." });

                // 4. Ensure directory exists
                string folder = Server.MapPath("~/Uploads/Users/");
                if (!Directory.Exists(folder))
                    Directory.CreateDirectory(folder);

                // 5. Save with unique name
                string fileName = Guid.NewGuid().ToString("N") + ext;
                string fullPath = Path.Combine(folder, fileName);
                file.SaveAs(fullPath);

                string relativePath = "/Uploads/Users/" + fileName;

                // 6. Return consistent JSON
                return Json(new
                {
                    StatusCode = 200,
                    Result = "Uploaded.",
                    imagePath = relativePath
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Log the error (use your logging framework)
                // e.g., logger.Error(ex, "Image upload failed");
                return Json(new
                {
                    StatusCode = 500,
                    Result = "Upload failed: " + ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        // ── Auth ────────────────────────────────────────────────────

        // POST /User/Login
        [HttpPost]
        public ActionResult Login(UserRequestModel req)
        {
            if (string.IsNullOrWhiteSpace(req.p_email) ||
                string.IsNullOrWhiteSpace(req.p_password_hash))
                return Json(new { StatusCode = 400, Message = "Email/Phone and password are required." });

            return Json(_user.Login(req.p_email, req.p_password_hash),
                        JsonRequestBehavior.AllowGet);
        }

        // POST /User/OAuthLogin
        [HttpPost]
        public ActionResult OAuthLogin(string providerName, string providerUserId,
                                       string email, string name)
        {
            if (string.IsNullOrWhiteSpace(email))
                return Json(new { StatusCode = 400, Message = "Email is required." });

            return Json(_user.OAuthLogin(providerName, providerUserId, email, name),
                        JsonRequestBehavior.AllowGet);
        }

        // POST /User/Register
        // No username in payload — auto-generated by SP.
        // Upload image first via /User/UploadImage, then include imagePath here.

        //[HttpPost]
        //public ActionResult Register(UserRequestModel req)
        //{
        //    if (string.IsNullOrWhiteSpace(req.p_email) ||
        //        string.IsNullOrWhiteSpace(req.p_password_hash))
        //        return Json(new { StatusCode = 400, Message = "Email and password are required." });

        //    return Json(_user.AddUser(req), JsonRequestBehavior.AllowGet);
        //}

        [HttpPost]
        public ActionResult Register(UserRequestModel req)
        {
            if (Request.Form["p_role_id"] != null && int.TryParse(Request.Form["p_role_id"], out int rid))
                req.p_role_id = rid;

            if (string.IsNullOrWhiteSpace(req.p_email) || string.IsNullOrWhiteSpace(req.p_password_hash))
                return Json(new { StatusCode = 400, Message = "Email and password are required." });

            var response = _user.AddUser(req);
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        // ── Phone OTP — Registration ────────────────────────────────

        // POST /User/SendPhoneOtp?phone=07XXXXXXXX
        [HttpPost]
        public ActionResult SendPhoneOtp(string phone)
        {
            if (string.IsNullOrWhiteSpace(phone))
                return Json(new { StatusCode = 400, Message = "Phone number is required." });
            return Json(_user.SendPhoneOtp(phone), JsonRequestBehavior.AllowGet);
        }

        // POST /User/VerifyPhoneOtp?phone=07XXXXXXXX&code=123456
        [HttpPost]
        public ActionResult VerifyPhoneOtp(string phone, string code)
        {
            if (string.IsNullOrWhiteSpace(phone) || string.IsNullOrWhiteSpace(code))
                return Json(new { StatusCode = 400, Message = "Phone and OTP code are required." });
            return Json(_user.VerifyPhoneOtp(phone, code), JsonRequestBehavior.AllowGet);
        }

        // ── Phone OTP — Edit Profile ────────────────────────────────

        // POST /User/SendEditOtp?userId=5
        [HttpPost]
        public ActionResult SendEditOtp(int userId)
        {
            return Json(_user.SendEditOtp(userId), JsonRequestBehavior.AllowGet);
        }

        // ── Forgot Password ─────────────────────────────────────────

        // POST /User/ForgotPassword?email=user@email.com
        // Step 1: sends OTP to registered phone. Returns ResultSet.{ phone, maskedPhone }.
        [HttpPost]
        public ActionResult ForgotPassword(string identifier, string deliveryMethod = "sms")
        {
            if (string.IsNullOrWhiteSpace(identifier))
                return Json(new { StatusCode = 400, Message = "Email or phone is required." });

            // deliveryMethod can be "sms", "email", or "whatsapp"
            return Json(_user.RequestPasswordReset(identifier, deliveryMethod), JsonRequestBehavior.AllowGet);
        }
        // POST /User/VerifyResetCode?phone=07XXXXXXXX&code=123456
        // Step 2: format check only, does NOT consume OTP.
        [HttpPost]
        public ActionResult VerifyResetCode(string phone, string code)
        {
            if (string.IsNullOrWhiteSpace(phone) || string.IsNullOrWhiteSpace(code))
                return Json(new { StatusCode = 400, Message = "Phone and OTP code are required." });
            return Json(_user.VerifyResetCode(phone, code), JsonRequestBehavior.AllowGet);
        }

        // POST /User/ResetPassword?phone=07XXXXXXXX&code=123456&newPassword=xxx
        // Step 3: verifies + consumes OTP, updates password.
        [HttpPost]
        public ActionResult ResetPassword(string identifier, string code, string newPassword)
        {
            if (string.IsNullOrWhiteSpace(identifier) || string.IsNullOrWhiteSpace(code) || string.IsNullOrWhiteSpace(newPassword))
                return Json(new { StatusCode = 400, Message = "All fields are required." });
            return Json(_user.ResetPassword(identifier, code, newPassword), JsonRequestBehavior.AllowGet);
        }

        // ── User CRUD ───────────────────────────────────────────────

        // GET /User/GetAll
        [HttpGet]
        public ActionResult GetAll()
            => Json(_user.GetAllUsers(), JsonRequestBehavior.AllowGet);

        // GET /User/GetById?id=1
        [HttpGet]
        public ActionResult GetById(int id)
            => Json(_user.GetUserById(id), JsonRequestBehavior.AllowGet);

        // GET /User/GetPending
        [HttpGet]
        public ActionResult GetPending()
            => Json(_user.GetPendingUsers(), JsonRequestBehavior.AllowGet);

        // POST /User/Edit
        [HttpPost]
        public ActionResult Edit(UserRequestModel req)
        {
            if (req.p_admin_id == null)
                return Json(new { StatusCode = 400, Message = "p_admin_id is required." });

            int loggedIn = req.p_admin_id.Value;
            bool isAdmin = _user.IsAdmin(loggedIn);

            if (!isAdmin && loggedIn != req.p_user_id)
                return Json(new { StatusCode = 403, Message = "You can only edit your own profile." });

            return Json(_user.EditUser(req));
        }

        // POST /User/Delete?id=1&adminId=1
        [HttpPost]
        public ActionResult Delete(int id, int adminId)
        {
            if (!_user.IsAdmin(adminId))
                return Json(new { StatusCode = 403, Message = "Unauthorized. Admin access required." });
            return Json(_user.DeleteUser(id, adminId));
        }

        // ── Admin Status Management ─────────────────────────────────

        // POST /User/ApproveUser
        // newStatus: "active" (approve) | "rejected" | "inactive" | "suspended" | "pending"
        [HttpPost]
        public ActionResult ApproveUser(int userId, int adminId, string newStatus,
                                        int roleId, string firstName = "", string lastName = "")
        {
            if (!_user.IsAdmin(adminId))
                return Json(new { StatusCode = 403, Message = "Unauthorized. Admin access required." });

            var valid = new[] { "active", "rejected", "inactive", "suspended", "pending" };
            if (string.IsNullOrWhiteSpace(newStatus) || Array.IndexOf(valid, newStatus) < 0)
                return Json(new { StatusCode = 400, Message = "Invalid status." });

            return Json(_user.ApproveOrRejectUser(userId, adminId, newStatus,
                                                   roleId, firstName, lastName));
        }

        // POST /User/ChangeUserStatus?userId=5&adminId=1&newStatus=suspended
        [HttpPost]
        public ActionResult ChangeUserStatus(int userId, int adminId, string newStatus)
        {
            if (!_user.IsAdmin(adminId))
                return Json(new { StatusCode = 403, Message = "Unauthorized. Admin access required." });

            var valid = new[] { "active", "inactive", "suspended", "pending", "rejected" };
            if (string.IsNullOrWhiteSpace(newStatus) || Array.IndexOf(valid, newStatus) < 0)
                return Json(new { StatusCode = 400, Message = "Invalid status." });

            return Json(_user.ChangeUserStatus(userId, adminId, newStatus));
        }

        // POST /User/ChangeLinkedStatus?userId=5&adminId=1&tableName=Member&newStatus=inactive
        [HttpPost]
        public ActionResult ChangeLinkedStatus(int userId, int adminId,
                                               string tableName, string newStatus)
        {
            if (!_user.IsAdmin(adminId))
                return Json(new { StatusCode = 403, Message = "Unauthorized. Admin access required." });

            if (tableName != "Member" && tableName != "Trainer")
                return Json(new { StatusCode = 400, Message = "tableName must be Member or Trainer." });

            return Json(_user.ChangeLinkedTableStatus(userId, adminId, tableName, newStatus));
        }

        // GET /User/HashPassword
        [HttpGet]
        public ActionResult HashPassword()
        {
            string password = "Password@123";
            string hash = BCrypt.Net.BCrypt.HashPassword(password);
            return Json(new { hash }, JsonRequestBehavior.AllowGet);
        }
    }
}