namespace GymManagement.Models
{
    public class UserModel
    {
        public int? userId { get; set; }
        public string username { get; set; }   // auto-generated, not shown in UI
        public string email { get; set; }
        public string phone { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string gender { get; set; }   // "Male" | "Female"
        public string profile_image { get; set; }   // e.g. /Uploads/Users/abc.jpg
        public int? roleId { get; set; }
        public string roleName { get; set; }
        public string status { get; set; }
        public string created_date { get; set; }
        public string updated_date { get; set; }
        public int? created_by { get; set; }
        public int? updated_by { get; set; }
    }

    public class UserRequestModel : BaseRequestModel
    {
        public int? p_user_id { get; set; }
        public string p_username { get; set; }   // NOT sent from UI — auto-generated by SP
        public string p_password_hash { get; set; }
        public string p_email { get; set; }
        public string p_phone { get; set; }
        public string p_first_name { get; set; }
        public string p_last_name { get; set; }
        public string p_gender { get; set; }   // "Male" | "Female"
        public string p_image_path { get; set; }   // saved file path from UploadImage
        public int? p_role_id { get; set; }
        public string p_status { get; set; }
        public string p_new_status { get; set; }
        public int? p_admin_id { get; set; }
        public string p_otp_code { get; set; }
        public string p_new_password { get; set; }
        public string p_provider { get; set; }
        public string p_provider_uid { get; set; }
        public string p_table_name { get; set; }   // "Member" | "Trainer" for action 016
    }
}