// ============================================================
//  Users.jsx — Admin user management
//  Changes:
//    • No username in Add User form — auto-generated by backend
//    • Gender dropdown in Add User and Edit modals
//    • Profile image upload in Add User modal (5 MB limit)
//    • Avatar shows profile image if available
//    • Approve = "active", Reject = "rejected" (not "inactive")
// ============================================================
import React, { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchUsers, editUserAction, deleteUser, approveUserAction } from '../actions';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import Badge from '../components/Badge';
import { formatDate } from '../utils';
import * as api from '../services/api';

const ROLE_LABELS = { 1: 'Admin', 2: 'Trainer', 3: 'Member' };
const ROLE_COLORS = { 1: 'var(--gym-accent)', 2: 'var(--gym-accent3)', 3: 'var(--gym-success)' };
const MAX_BYTES   = 5 * 1024 * 1024; // 5 MB

function FieldGroup({ label, children }) {
  return <div><label className="gym-label">{label}</label>{children}</div>;
}

const initEdit = {
  p_user_id: '', p_email: '', p_phone: '',
  p_first_name: '', p_last_name: '',
  p_gender: '', p_role_id: '3', p_status: 'active',
};

const initAdd = {
  email: '', phone: '', firstName: '', lastName: '',
  gender: '', password: '', role_id: '3',
};

export default function Users() {
  const dispatch = useDispatch();
  const { data, loading } = useSelector((s) => s.users);
  const adminId = useSelector((s) => s.ui.currentUserId);

  const [showEdit,   setShowEdit]   = useState(false);
  const [showCard,   setShowCard]   = useState(false);
  const [showAdd,    setShowAdd]    = useState(false);
  const [cardData,   setCardData]   = useState(null);
  const [editForm,   setEditForm]   = useState(initEdit);
  const [addForm,    setAddForm]    = useState(initAdd);
  const [saving,     setSaving]     = useState(false);
  const [addSaving,  setAddSaving]  = useState(false);
  const [addError,   setAddError]   = useState('');
  const [search,     setSearch]     = useState('');
  const [roleFilter, setRoleFilter] = useState('all');
  const [statFilter, setStatFilter] = useState('all');
  const [showAddPass,setShowAddPass]= useState(false);

  // ── Add modal image state ──────────────────────────────────
  const [addImagePreview,   setAddImagePreview]   = useState('');
  const [addImagePath,      setAddImagePath]      = useState('');
  const [addImageError,     setAddImageError]     = useState('');
  const [addImageUploading, setAddImageUploading] = useState(false);
  const addFileRef = useRef(null);

  useEffect(() => { dispatch(fetchUsers()); }, [dispatch]);

  const handleChange    = (e) => setEditForm((f) => ({ ...f, [e.target.name]: e.target.value }));
  const handleAddChange = (e) => { setAddError(''); setAddForm((f) => ({ ...f, [e.target.name]: e.target.value })); };

  // ── Add modal image handlers ───────────────────────────────
  const handleAddImage = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setAddImageError('');
    if (file.size > MAX_BYTES) { setAddImageError(`Max ${MAX_BYTES/1024/1024} MB.`); addFileRef.current.value=''; return; }
    const allowed = ['image/jpeg','image/png','image/webp'];
    if (!allowed.includes(file.type)) { setAddImageError('JPG, PNG or WebP only.'); addFileRef.current.value=''; return; }
    const reader = new FileReader();
    reader.onload = (ev) => setAddImagePreview(ev.target.result);
    reader.readAsDataURL(file);
    setAddImageUploading(true);
    try {
      const res  = await api.uploadUserImage(file);
      const d    = res.data;
      if (d?.StatusCode === 200) { setAddImagePath(d.imagePath); }
      else { setAddImageError(d?.Result || 'Upload failed.'); setAddImagePreview(''); }
    } catch { setAddImageError('Upload failed.'); setAddImagePreview(''); }
    setAddImageUploading(false);
  };

  const removeAddImage = () => {
    setAddImagePreview(''); setAddImagePath(''); setAddImageError('');
    if (addFileRef.current) addFileRef.current.value = '';
  };

  // ── Edit open ──────────────────────────────────────────────
  const handleEditOpen = (row) => {
    setEditForm({
      p_user_id:    row.userId,
      p_email:      row.email      || '',
      p_phone:      row.phone      || '',
      p_first_name: row.firstName  || '',
      p_last_name:  row.lastName   || '',
      p_gender:     row.gender     || '',
      p_role_id:    String(row.roleId || 3),
      p_status:     row.status     || 'active',
    });
    setShowEdit(true);
  };

  const handleEditSave = async () => {
    setSaving(true);
    const ok = await dispatch(editUserAction(editForm, adminId));
    setSaving(false);
    if (ok) setShowEdit(false);
  };

  const handleDelete = (id, name) => {
    if (window.confirm(`Delete user "${name}"?`)) dispatch(deleteUser(id, adminId));
  };

  // Approve = set to "active", Reject = set to "rejected"
  const handleApprove = (id, roleId) => dispatch(approveUserAction(id, adminId, 'active',   roleId));
  const handleReject  = (id, roleId) => dispatch(approveUserAction(id, adminId, 'rejected', roleId));

  // ── Add User submit ────────────────────────────────────────
  const handleAddUser = async () => {
    const { email, phone, firstName, lastName, gender, password, role_id } = addForm;
    if (!firstName.trim()) { setAddError('First name is required.'); return; }
    if (!lastName.trim())  { setAddError('Last name is required.'); return; }
    if (!email.trim())     { setAddError('Email is required.'); return; }
    if (!gender)           { setAddError('Please select gender.'); return; }
    if (!password)         { setAddError('Password is required.'); return; }
    if (password.length < 6) { setAddError('Password must be at least 6 characters.'); return; }
    if (phone && !/^(\+\d{10,14}|0\d{9})$/.test(phone))
      { setAddError('Enter a valid phone: 0771234567 or +94771234567'); return; }

    setAddSaving(true); setAddError('');
    try {
      const res  = await api.registerUser({
        p_first_name:    firstName.trim(),
        p_last_name:     lastName.trim(),
        p_email:         email.trim(),
        p_phone:         phone.trim() || '',
        p_gender:        gender,
        p_password_hash: password,
        p_role_id:       parseInt(role_id, 10),
        p_image_path:    addImagePath || '',
      });
      const d = res.data;
      if (d?.StatusCode === 200 || d?.StatusCode === 201) {
        dispatch({ type:'SHOW_TOAST', payload:{ message:'User created!', type:'success', id:Date.now() } });
        dispatch(fetchUsers());
        setShowAdd(false);
        setAddForm(initAdd);
        removeAddImage();
      } else {
        setAddError(d?.Result || d?.Message || 'Failed to create user.');
      }
    } catch { setAddError('Could not connect to server.'); }
    setAddSaving(false);
  };

  const openAddModal = () => {
    setAddForm(initAdd); setAddError(''); removeAddImage(); setShowAdd(true);
  };

  // ── Avatar helper ──────────────────────────────────────────
  const Avatar = ({ row, size = 8 }) => {
    const color = ROLE_COLORS[row.roleId] || 'var(--gym-accent)';
    const initials = ((row.firstName || row.username || '?').charAt(0)).toUpperCase();
    if (row.profile_image) {
      return (
        <img src={row.profile_image} alt={initials}
             className={`w-${size} h-${size} rounded-lg object-cover flex-shrink-0`} />
      );
    }
    return (
      <div className={`w-${size} h-${size} rounded-lg flex items-center justify-center text-xs font-bold flex-shrink-0`}
           style={{ background: color+'22', color }}>
        {initials}
      </div>
    );
  };

  // ── Filters ────────────────────────────────────────────────
  let filtered = data;
  if (search) filtered = filtered.filter((u) =>
    (u.firstName || '').toLowerCase().includes(search.toLowerCase()) ||
    (u.lastName  || '').toLowerCase().includes(search.toLowerCase()) ||
    (u.email     || '').toLowerCase().includes(search.toLowerCase()) ||
    (u.username  || '').toLowerCase().includes(search.toLowerCase())
  );
  if (roleFilter !== 'all') filtered = filtered.filter((u) => String(u.roleId) === roleFilter);
  if (statFilter !== 'all') filtered = filtered.filter((u) => (u.status||'').toLowerCase() === statFilter);

  const pendingCount = data.filter((u) => (u.status||'').toLowerCase() === 'pending').length;

  const statusVariant = (s='') => {
    const l = s.toLowerCase();
    if (l==='active')    return 'active';
    if (l==='pending')   return 'pending';
    if (l==='inactive')  return 'inactive';
    if (l==='suspended') return 'inactive';
    if (l==='rejected')  return 'inactive';
    return 'default';
  };

  const columns = [
    { key:'userId', label:'ID', width:60, render:(v) => <span className="id-chip">#{v}</span> },
    { key:'firstName', label:'Name', render:(v, row) => (
      <button className="flex items-center gap-2 text-left"
              onClick={() => { setCardData(row); setShowCard(true); }}
              style={{ background:'none', border:'none', cursor:'pointer' }}>
        <Avatar row={row} size={8} />
        <div>
          <div className="font-medium text-sm" style={{ color:'var(--gym-text)' }}>
            {row.firstName || ''} {row.lastName || ''}
          </div>
          <div className="text-xs" style={{ color:'var(--gym-muted)' }}>@{row.username}</div>
        </div>
      </button>
    )},
    { key:'email',  label:'Email', render:(v) => <span className="text-xs" style={{ color:'var(--gym-muted)' }}>{v}</span> },
    { key:'phone',  label:'Phone', render:(v) => v || '—' },
    { key:'gender', label:'Gender', render:(v) => v ? (
      <span className="text-xs px-2 py-0.5 rounded-full"
            style={{ background:v==='Male'?'rgba(71,147,255,.12)':'rgba(255,71,200,.12)',
                     color:v==='Male'?'#4793ff':'#ff47c8' }}>
        {v==='Male'?'♂':'♀'} {v}
      </span>
    ) : '—' },
    { key:'roleId', label:'Role', render:(v) => (
      <span className="text-xs font-bold px-2 py-0.5 rounded-full"
            style={{ background:(ROLE_COLORS[v]||'var(--gym-muted)')+'22', color:ROLE_COLORS[v]||'var(--gym-muted)' }}>
        {ROLE_LABELS[v]||'Unknown'}
      </span>
    )},
    { key:'status',       label:'Status', render:(v) => <Badge variant={statusVariant(v)}>{v||'active'}</Badge> },
    { key:'created_date', label:'Joined',  render:(v) => <span className="text-xs" style={{ color:'var(--gym-muted)' }}>{formatDate(v)}</span> },
    { key:'_actions', label:'Actions', render:(_, row) => {
      const st = (row.status||'').toLowerCase();
      return (
        <div className="flex gap-1 flex-wrap">
          {st === 'pending' && <>
            <button className="btn btn-secondary btn-sm" style={{ color:'var(--gym-success)' }}
                    onClick={() => handleApprove(row.userId, row.roleId)}>✓ Approve</button>
            <button className="btn btn-danger btn-sm"
                    onClick={() => handleReject(row.userId, row.roleId)}>✕ Reject</button>
          </>}
          <select className="gym-input text-xs py-1 px-2" style={{ width:115 }}
                  value={row.status||'active'}
                  onChange={(e) => dispatch(approveUserAction(row.userId, adminId, e.target.value, row.roleId))}>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
            <option value="suspended">Suspended</option>
            <option value="pending">Pending</option>
          </select>
          <button className="btn btn-secondary btn-sm" onClick={() => handleEditOpen(row)}>✏️ Edit</button>
          <button className="btn btn-danger btn-sm"
                  onClick={() => handleDelete(row.userId, row.firstName||row.username)}>🗑️</button>
        </div>
      );
    }},
  ];

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="page-header">
        <div>
          <div className="page-title">Users</div>
          <div className="page-sub">
            {data.length} users registered
            {pendingCount > 0 && (
              <span className="ml-2 px-2 py-0.5 rounded-full text-xs font-bold"
                    style={{ background:'rgba(255,179,71,.15)', color:'var(--gym-warning)' }}>
                ⏳ {pendingCount} pending approval
              </span>
            )}
          </div>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-primary" onClick={openAddModal}
                  style={{ display:'flex', alignItems:'center', gap:'6px' }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" width="16" height="16"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>
            Add User
          </button>
          <button className="btn btn-secondary" onClick={() => dispatch(fetchUsers())}>↺ Refresh</button>
        </div>
      </div>

      {/* Pending banner */}
      {pendingCount > 0 && (
        <div className="p-4 rounded-xl flex items-center gap-3"
             style={{ background:'rgba(255,179,71,.08)', border:'1px solid rgba(255,179,71,.2)' }}>
          <span className="text-2xl">⏳</span>
          <div>
            <div className="font-semibold text-sm" style={{ color:'var(--gym-warning)' }}>
              {pendingCount} user{pendingCount>1?'s':''} waiting for approval
            </div>
            <div className="text-xs mt-0.5" style={{ color:'var(--gym-muted)' }}>
              Filter by "Pending" status to review and approve/reject registrations.
            </div>
          </div>
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-3">
        <div className="relative">
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs" style={{ color:'var(--gym-muted)' }}>🔍</span>
          <input className="gym-input pl-8 w-52"
                 placeholder="Search name, email..."
                 value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <select className="gym-input w-32" value={roleFilter} onChange={(e) => setRoleFilter(e.target.value)}>
          <option value="all">All Roles</option>
          <option value="1">Admin</option>
          <option value="2">Trainer</option>
          <option value="3">Member</option>
        </select>
        <select className="gym-input w-36" value={statFilter} onChange={(e) => setStatFilter(e.target.value)}>
          <option value="all">All Status</option>
          <option value="active">Active</option>
          <option value="pending">Pending</option>
          <option value="inactive">Inactive</option>
          <option value="suspended">Suspended</option>
          <option value="rejected">Rejected</option>
        </select>
      </div>

      <DataTable columns={columns} data={filtered} loading={loading} rowKey="userId" />

      {/* ── Add User Modal ── */}
      <Modal isOpen={showAdd} onClose={() => setShowAdd(false)} title="+ ADD USER" maxWidth={500}>
        <div className="modal-body space-y-4">

          {/* Profile image */}
          <div>
            <label className="gym-label">Profile Photo <span style={{ color:'var(--gym-muted)' }}>(optional, max 5 MB)</span></label>
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-xl flex-shrink-0 overflow-hidden flex items-center justify-center"
                   style={{ background:'var(--gym-surface2)', border:'2px dashed var(--gym-border)', cursor:'pointer' }}
                   onClick={() => !addImageUploading && addFileRef.current?.click()}>
                {addImagePreview
                  ? <img src={addImagePreview} alt="preview" className="w-full h-full object-cover" />
                  : <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" width="20" height="20" style={{ color:'var(--gym-muted)' }}>
                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/>
                    </svg>}
              </div>
              <div>
                <input ref={addFileRef} type="file" accept=".jpg,.jpeg,.png,.webp" className="hidden" onChange={handleAddImage} />
                {!addImagePreview
                  ? <button type="button" className="btn btn-secondary text-sm"
                             onClick={() => addFileRef.current?.click()} disabled={addImageUploading}>
                      {addImageUploading ? 'Uploading…' : '📷 Choose'}
                    </button>
                  : <div className="flex items-center gap-2">
                      <span className="text-xs" style={{ color: addImageUploading?'var(--gym-muted)':'var(--gym-success)' }}>
                        {addImageUploading?'⏳ Uploading…':'✓ Ready'}
                      </span>
                      <button type="button" className="btn btn-danger btn-sm text-xs" onClick={removeAddImage}>✕</button>
                    </div>}
                <p className="text-xs mt-1" style={{ color:'var(--gym-muted)' }}>JPG, PNG or WebP · max 5 MB</p>
              </div>
            </div>
            {addImageError && <p className="text-xs mt-1" style={{ color:'var(--gym-accent2)' }}>⚠ {addImageError}</p>}
          </div>

          {/* Name */}
          <div className="grid grid-cols-2 gap-3">
            <FieldGroup label="First Name *">
              <input className="gym-input" name="firstName" value={addForm.firstName} onChange={handleAddChange} placeholder="First name" />
            </FieldGroup>
            <FieldGroup label="Last Name *">
              <input className="gym-input" name="lastName" value={addForm.lastName} onChange={handleAddChange} placeholder="Last name" />
            </FieldGroup>
          </div>

          {/* Gender */}
          <FieldGroup label="Gender *">
            <div className="flex gap-3">
              {['Male','Female'].map((g) => (
                <label key={g} className="flex items-center gap-2 cursor-pointer flex-1 px-3 py-2 rounded-xl transition-all"
                       style={{ border:`1px solid ${addForm.gender===g?'var(--gym-accent)':'var(--gym-border)'}`,
                                background: addForm.gender===g?'rgba(232,255,71,.08)':'var(--gym-surface)' }}>
                  <input type="radio" name="gender" value={g} checked={addForm.gender===g} onChange={handleAddChange} className="hidden" />
                  <span style={{ fontSize:14 }}>{g==='Male'?'♂':'♀'}</span>
                  <span className="text-sm" style={{ color:addForm.gender===g?'var(--gym-accent)':'var(--gym-text)' }}>{g}</span>
                </label>
              ))}
            </div>
          </FieldGroup>

          {/* Email & Phone */}
          <FieldGroup label="Email *">
            <input className="gym-input" name="email" type="email" value={addForm.email} onChange={handleAddChange} placeholder="Email address" />
          </FieldGroup>
          <FieldGroup label="Phone">
            <input className="gym-input" name="phone" type="tel"
                   value={addForm.phone}
                   onChange={(e) => { setAddError(''); setAddForm((f) => ({ ...f, phone: e.target.value.replace(/[^\d+]/g,'').slice(0,15) })); }}
                   placeholder="0771234567 or +94771234567" />
            {addForm.phone && !/^(\+\d{10,14}|0\d{9})$/.test(addForm.phone) && addForm.phone.length > 0 && (
              <p className="text-xs mt-1" style={{ color:'var(--gym-accent2)' }}>⚠ Use 0771234567 or +94771234567</p>
            )}
          </FieldGroup>

          {/* Password */}
          <FieldGroup label="Password *">
            <div className="relative">
              <input className="gym-input pr-10" name="password"
                     type={showAddPass?'text':'password'}
                     value={addForm.password} onChange={handleAddChange}
                     placeholder="Min. 6 characters" />
              <button type="button" onClick={() => setShowAddPass((p)=>!p)}
                      className="absolute right-3 top-1/2 -translate-y-1/2"
                      style={{ background:'none',border:'none',color:'var(--gym-muted)',cursor:'pointer' }}>
                {showAddPass
                  ? <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="15" height="15"><path d="M17.94 17.94A10.07 10.07 0 0112 20c-7 0-11-8-11-8a18.45 18.45 0 015.06-5.94M9.9 4.24A9.12 9.12 0 0112 4c7 0 11 8 11 8a18.5 18.5 0 01-2.16 3.19m-6.72-1.07a3 3 0 11-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
                  : <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" width="15" height="15"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>}
              </button>
            </div>
          </FieldGroup>

          {/* Role */}
          <FieldGroup label="Role">
            <select className="gym-input" name="role_id" value={addForm.role_id} onChange={handleAddChange}>
              <option value="1">Admin</option>
              <option value="2">Trainer</option>
              <option value="3">Member</option>
            </select>
          </FieldGroup>

          {addError && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-xl text-sm"
                 style={{ background:'rgba(255,71,71,.08)',border:'1px solid rgba(255,71,71,.22)',color:'var(--gym-accent2)' }}>
              <span>⚠</span> {addError}
            </div>
          )}
        </div>
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={() => setShowAdd(false)}>Cancel</button>
          <button className="btn btn-primary" onClick={handleAddUser} disabled={addSaving||addImageUploading}>
            {addSaving ? 'Creating…' : '+ Create User'}
          </button>
        </div>
      </Modal>

      {/* ── Edit Modal ── */}
      <Modal isOpen={showEdit} onClose={() => setShowEdit(false)} title="EDIT USER" maxWidth={460}>
        <div className="modal-body space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <FieldGroup label="First Name">
              <input className="gym-input" name="p_first_name" value={editForm.p_first_name} onChange={handleChange} />
            </FieldGroup>
            <FieldGroup label="Last Name">
              <input className="gym-input" name="p_last_name" value={editForm.p_last_name} onChange={handleChange} />
            </FieldGroup>
          </div>
          <FieldGroup label="Gender">
            <div className="flex gap-3">
              {['Male','Female'].map((g) => (
                <label key={g} className="flex items-center gap-2 cursor-pointer flex-1 px-3 py-2 rounded-xl"
                       style={{ border:`1px solid ${editForm.p_gender===g?'var(--gym-accent)':'var(--gym-border)'}`,
                                background:editForm.p_gender===g?'rgba(232,255,71,.08)':'var(--gym-surface)' }}>
                  <input type="radio" name="p_gender" value={g} checked={editForm.p_gender===g} onChange={handleChange} className="hidden" />
                  <span style={{ fontSize:14 }}>{g==='Male'?'♂':'♀'}</span>
                  <span className="text-sm" style={{ color:editForm.p_gender===g?'var(--gym-accent)':'var(--gym-text)' }}>{g}</span>
                </label>
              ))}
            </div>
          </FieldGroup>
          <div className="grid grid-cols-2 gap-4">
            <FieldGroup label="Phone">
              <input className="gym-input" name="p_phone" value={editForm.p_phone} onChange={handleChange} />
            </FieldGroup>
            <FieldGroup label="Email">
              <input className="gym-input" name="p_email" type="email" value={editForm.p_email} onChange={handleChange} />
            </FieldGroup>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <FieldGroup label="Role">
              <select className="gym-input" name="p_role_id" value={editForm.p_role_id} onChange={handleChange}>
                <option value="1">Admin</option>
                <option value="2">Trainer</option>
                <option value="3">Member</option>
              </select>
            </FieldGroup>
            <FieldGroup label="Status">
              <select className="gym-input" name="p_status" value={editForm.p_status} onChange={handleChange}>
                <option value="active">Active</option>
                <option value="inactive">Inactive</option>
                <option value="suspended">Suspended</option>
                <option value="pending">Pending</option>
                <option value="rejected">Rejected</option>
              </select>
            </FieldGroup>
          </div>
        </div>
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={() => setShowEdit(false)}>Cancel</button>
          <button className="btn btn-primary" onClick={handleEditSave} disabled={saving}>
            {saving ? 'Saving...' : 'Save Changes'}
          </button>
        </div>
      </Modal>

      {/* ── View Card ── */}
      <Modal isOpen={showCard} onClose={() => setShowCard(false)} title="USER PROFILE" maxWidth={420}>
        {cardData && (
          <div className="modal-body">
            <div className="flex items-center gap-4 mb-5">
              <div className="w-16 h-16 rounded-2xl overflow-hidden flex items-center justify-center flex-shrink-0"
                   style={{ background:(ROLE_COLORS[cardData.roleId]||'var(--gym-accent)')+'22' }}>
                {cardData.profile_image
                  ? <img src={cardData.profile_image} alt="avatar" className="w-full h-full object-cover" />
                  : <span className="text-2xl font-bold" style={{ color:ROLE_COLORS[cardData.roleId]||'var(--gym-accent)', fontFamily:"'Space Mono', monospace" }}>
                      {(cardData.firstName||cardData.username||'?').charAt(0).toUpperCase()}
                    </span>}
              </div>
              <div>
                <div className="text-xl font-bold" style={{ color:'var(--gym-text)' }}>
                  {cardData.firstName} {cardData.lastName}
                </div>
                <div className="text-xs" style={{ color:'var(--gym-muted)' }}>@{cardData.username}</div>
                <div className="text-sm mt-0.5" style={{ color:ROLE_COLORS[cardData.roleId]||'var(--gym-muted)' }}>
                  {ROLE_LABELS[cardData.roleId]||'Unknown'} · <Badge variant={statusVariant(cardData.status)}>{cardData.status}</Badge>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-2 gap-3">
              {[
                ['Email',   cardData.email],
                ['Phone',   cardData.phone],
                ['Gender',  cardData.gender],
                ['Role ID', cardData.roleId],
                ['User ID', cardData.userId],
                ['Joined',  formatDate(cardData.created_date)],
                ['Updated', formatDate(cardData.updated_date)],
              ].map(([k,v]) => (
                <div key={k} className="p-3 rounded-xl" style={{ background:'var(--gym-surface2)' }}>
                  <div className="text-xs mb-0.5" style={{ color:'var(--gym-muted)' }}>{k}</div>
                  <div className="text-sm font-medium truncate" style={{ color:'var(--gym-text)' }}>{v||'—'}</div>
                </div>
              ))}
            </div>
          </div>
        )}
        <div className="modal-footer">
          <button className="btn btn-secondary" onClick={() => setShowCard(false)}>Close</button>
          {cardData && (
            <button className="btn btn-primary" onClick={() => { handleEditOpen(cardData); setShowCard(false); }}>
              Edit User
            </button>
          )}
        </div>
      </Modal>
    </div>
  );
}